version: '3.3'
services:
  geoloc-database:
    image: postgres:10.3
    volumes:
      - ~/.docker/volumes/geoloc/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: geoloc
      POSTGRES_USER: ${GEOLOC_POSTGRES_USER}
      POSTGRES_PASSWORD: ${GEOLOC_POSTGRES_PASSWORD}
    expose:
      - 5432
    networks:
      - geoloc-local
    restart: unless-stopped

  geoloc-service:
    build:
      context: .
    ports:
      - "11000:8080"
    environment:
      - GOOGLE_GEOLOCATION_API=${GOOGLE_GEOLOCATION_API}
      - GOOGLE_GEOLOCATION_KEY=${GOOGLE_GEOLOCATION_KEY}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://geoloc-database:5432/geoloc
      - SPRING_DATASOURCE_USERNAME=${GEOLOC_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${GEOLOC_POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${GEOLOC_ACTIVE_PROFILES}
    depends_on:
      - geoloc-database
    networks:
      - geoloc-local
    restart: unless-stopped

networks:
  geoloc-local:
    driver: bridge
